version: "3.9"
services:
  pgMaster:
    image: postgres:14.8
    restart: always
    container_name: pg-master
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
    volumes:
      - master-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    user: postgres
volumes:
  master-data:

